[package]
name = "themeparks"
version = "0.1.0"
edition = "2021"

authors = ["Rafael Macedo <macedo.rafaelfernandes@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
